### ISSUE TITLE
Product text

### ISSUE THREAD

**Issue by JuliaJRH** [JuliaJRH/journosalarysharer#3]
## Text for survey section

I am a [ job title ]
and I get paid
$[ ##,### ] 
a year. 

I’ve been doing [ field dropdown ] 
for [ ## ] years. 
The company I work for is
||  Just me  ||  Small (2-20 editorial staff)  ||  Medium (20-100)  ||  Large (100+)  ||
and the cost of living where I am is
||  Low (Dayton, Memphis, Oklahoma City, etc.)  ||  Medium (Minneapolis, Phoenix, Portland, etc.)  ||  High (New York City, San Francisco, Honolulu, etc.)  ||

Did you negotiate for your current salary?
|| Yes, successfully || Yes, unsuccessfully || No ||
One demographic question to wrap it up:
You are a [race/ethnicity dropdown?] [gender dropdown/autocomplete] 
in your [age group dropdown]

---
## Text for about (?)

Why share your salary information? 

Sharing your salary with others is helpful in starting a discussion that can benefit everyone involved by preparing you for salary negotiations, giving you a sense of the salaries made by others in similar roles with similar experiences. After you enter your information on this page, I'll walk you through a few ways to start a salary conversation with your friends or colleagues. 

How are you using this information? 

This information is being used in two ways: First: To share back to you and others who use the tool to give you a sense of others' salaries. Second: For a graduate school project, as research. 

Who are you? 

I'm Julia Haslanger, a graduate student in journalism at CUNY. My focus is creating things that would be useful for journalists, particulary journalists in new roles, like social media editors.

---
## Text for sharing section

Now on a scale from "hell no" to "oh sure," how do you feel about telling other people how much you make? 
|| Not a chance || Maybe if someone I trust asks || Convince me || Only with specific people || I'm game, NBD ||
## Text for slider

Option 1: Not a chance
Fair enough. Would you mind sharing a link to this survey for research purposes, if nothing else? 

Option 1 accompanying share text: 

---

Option 2: Maybe if someone I trust asks

Option 2 accompanying share text: 

---

Option 3: Convince me

Option 3 accompanying share text: 

---

Option 4: Only with specific people

Option 4 accompanying share text: 

---

Option 5: I'm game, NBD

Option 5 accompanying share text: 

---
## Text for sharing email

Before you go...

We’d like to be able to tell you how your salary compares to others in your field, but we’re not quite ready. If you would like to get an email from us once we have enough responses to be statistically useful, enter your email:

[ email@email.com ]
|| Submit ||

**Comment by jueyang** [comment]
Sharing page is live. I've used copies I could find in the wireframe. @JuliaJRH you can fill up the rest of the text in the html markup.

For area 1 contexts:
https://github.com/JuliaJRH/journosalarysharer/blob/gh-pages/sharing.html#L72

For sharing text:
https://github.com/JuliaJRH/journosalarysharer/blob/gh-pages/sharing.html#L88

**Comment by JuliaJRH** [comment]
Thanks so much! Working on filling in that text now.
