### ISSUE TITLE
Working with CSS to make form text resemble wireframe

### ISSUE THREAD

**Issue by JuliaJRH** [JuliaJRH/journosalarysharer#6]
**Key points**
- [x] Centering form questions (I tried putting it in a div with a class of center-block but it didn't work)
- [x] Responsive (or at least designed for mobile first)
- [ ] Decreasing the size of the heading for Demographic questions
- [x] Removing the bullets before each option (keeping the radio buttons, of course, since those have a function)
- [ ] Better establishing helper text as helper text (italics or smaller or something)

**Comment by jueyang** [comment]
@JuliaJRH :cool: Are you working on the CSS now, or would you like me to take a look at these (since you assigned it to me)?

**Comment by JuliaJRH** [comment]
@jueyang Could you take a look? I tried to fix up the few things that I could figure out, but I think I hit the point where it was time to had it over to the designer.

**Comment by jueyang** [comment]
Will do. I'll do a pull request this week.

**Comment by jueyang** [comment]
Hey @JuliaJRH, did a few things in another branch. Let's chat about some other implementations today (like the graying out when a question is not active) and update the backlog.

**Comment by jueyang** [comment]
See #8. closing this.
