### ISSUE TITLE
Begin developing sharing slider

### ISSUE THREAD

**Issue by JuliaJRH** [JuliaJRH/journosalarysharer#7]
**Key points**
To fork: http://juliajrh.github.io/journosalarysharer/sharing 
- [x] A slider with 5 stops
- [x] Short text below each stop 
  - || Not a chance || 
  - || Maybe if someone I trust asks || 
  - || Convince me || 
  - || Only with specific people || 
  - || I'm game, NBD ||
- [x] An area for a block of text that will change depending on which stop the slider is at. (Area 1: this is the context text)
- [x] A second area for another block of text that will change depending on which stop the slider is at. (Area 2: this is the sharing text)

**Next step**
- [x] Integrating two share buttons into Area 2. 
  - Copy to clipboard
  - Twitter
- [ ] Pulling information from the survey response to populate Area 2. 
  - Salary number
  - Job title

**Comment by jueyang** [comment]
The only item left one is pulling numbers of salary from the previous page to populate the text.

It takes a bit longer. Since the main functionalities are done, let's move this item to the next phase. New ticket here. #12
